### ISSUE TITLE
When Lunatic is in play, Minions see the Lunatic as the Demon instead of the actual Demon

### ISSUE THREAD

**Issue by wmgroot** [sionar/Botc#1]
Tested on version 20.10.9 in base Bad Moon Rising setup using the night helper tool.

Currently we have to manually send the Evil Info step as a storyteller as a workaround in order to keep the game honest.

**Comment by sionar** [comment]
When characters tokens are dealt to players, the real demon gets the Lunatic token to emulate how the Lunatic is ran in real life games. So if a player sees that they're the Lunatic, they should know that they're the actual demon. For more information on how to run the Lunatic, check the page on 'How to Setup a Lunatic Game' in the Storyteller Manual inside the mod.
